<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SharedKernel.Domain">
      <HintPath>..\..\SharedKernel\SharedKernel.Domain.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
